### ISSUE TITLE
java.lang.NoClassDefFoundError java.nio.charset.StandardCharsets

### ISSUE THREAD

**Issue by felipeaugusto1** [loopme/loopme-android-sdk#10]
```at com.loopme.common.Utils.getUrlEncodedString(Utils.java:401)
       at com.loopme.request.AdRequestParametersProvider.setDeviceName(AdRequestParametersProvider.java:524)
       at com.loopme.request.AdRequestParametersProvider.init(AdRequestParametersProvider.java:518)
       at com.loopme.BaseAd.<init>(BaseAd.java:81)
       at com.loopme.LoopMeInterstitial.<init>(LoopMeInterstitial.java:64)
       at com.loopme.LoopMeAdHolder.getInterstitial(LoopMeAdHolder.java:39)
       at com.loopme.LoopMeInterstitial.getInstance(LoopMeInterstitial.java:83)
       at com.cakecodes.adwaterfall.a.k.<init>(LoopMe.java:29)
       at com.cakecodes.adwaterfall.b.a.a(AdController.java:140)
       at com.cakecodes.bitmaker.activity.MainActivity.r(MainActivity.java:974)
       at com.cakecodes.bitmaker.activity.MainActivity.c(MainActivity.java:118)
       at com.cakecodes.bitmaker.activity.MainActivity$25.onPreExecute(MainActivity.java:800)
       at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:586)
       at android.os.AsyncTask.execute(AsyncTask.java:534)
       at com.cakecodes.bitmaker.activity.MainActivity.p(MainActivity.java:871)
       at com.cakecodes.bitmaker.activity.MainActivity.onResume(MainActivity.java:351)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1184)
       at android.app.Activity.performResume(Activity.java:5082)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2573)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2611)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2097)
       at android.app.ActivityThread.access$600(ActivityThread.java:133)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4794)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
       at dalvik.system.NativeStart.main(NativeStart.java)```

**Comment by katrin010692** [comment]
Fixed. Please update loopme-sdk to version 5.2.
