### ISSUE TITLE
 No static method checkSelfPermission

### ISSUE THREAD

**Issue by Scanor** [loopme/loopme-android-sdk#2]
I start up my app which has integrated loopme-android-sdk, and I get this error: No static method checkSelfPermission.  
Here is the log:
`java.lang.NoSuchMethodError: No static method checkSelfPermission(Landroid/content/Context;Ljava/lang/String;)I in class Landroid/support/v4/content/ContextCompat; or its super classes (declaration of 'android.support.v4.content.ContextCompat' appears in /data/app/com.miniant.browser-2/base.apk)
                                                                         at com.loopme.data.DataCollector.detectAccounts(DataCollector.java:122)
                                                                         at com.loopme.data.DataCollector.onReceive(DataCollector.java:136)
                                                                         at com.loopme.data.LoopMeReceiver.onReceive(LoopMeReceiver.java:27)
                                                                         at android.app.ActivityThread.handleReceiver(ActivityThread.java:2886)
                                                                         at android.app.ActivityThread.access$1700(ActivityThread.java:178)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                         at android.os.Looper.loop(Looper.java:194)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5692)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)`

**Comment by Scanor** [comment]
ok,I solve this issues myself by upgrade compileSdkVersion to 23.
